blank_issues_enabled: false
contact_links:
  - name: 💬 Installation instructions / Инструкция по установке 
    url: https://github.com/hamptik/zapret-openwrt/blob/zap1/docs/Installing-zapret-openwrt-package.md
    about: Installation instructions / Инструкция по установке

  - name: 📚 Original documetation / Оригинальная документация к zapret'у
    url: https://github.com/bol-van/zapret/blob/master/docs/readme.md
    about: README zapret
